apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
metadata:
  name: {{ .Values.dev.database.secret.name }}
  namespace: {{ .Values.dev.namespace }}
data:
  password: {{ .Values.dev.database.secret.password }}
  username: {{ .Values.dev.database.secret.username }}